name: CLIENT001 TESTING WORKFLOW
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: client001
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update TestCaseInputDriver json file
        uses: microsoft/variable-substitution@v1
        with:
          files: './src/test/resources/ClientTestCaseDriverFiles/TestCaseInputDriver.json'
        env:
          TestCaseRunConfiguration: ${{ vars.CLIENT001_TESTCASE_RUN_DETAILS }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Import core library
        run: mvn -s settings.xml install -DskipTests
        env:
          MAVEN_USER: ${{ secrets.OWNER_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.OWNER_TOKEN }}

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Chrome dependencies
        run: |
          sudo apt-get install -y \
            libnss3 \
            libgconf-2-4 \
            libxss1 \
            libasound2 \
            fonts-liberation \
            xdg-utils

      - name: Run test cases
        run: mvn clean compile test --file pom.xml